# 如需自定义，复制此文件为 config.yaml 进行配置
# 更新配置后需要重启

# chromium 地址，可填写系统的edge/chromium路径，例如（根据实际情况调整）：
# chromiumPath: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
chromiumPath:

# headless
headless: true

# puppeteer启动args，注意args的--前缀
args:
  - --disable-gpu
  - --disable-setuid-sandbox
  - --no-sandbox
  - --no-zygote